<script lang="ts">
  import { formatPaisa } from '$lib/format';
  let { data, form } = $props();
  let names = $derived(new Map(data.balances.map((b) => [b.userId, b.name])));
  let selected = $state<string | null>(null);
  let payment = $derived(data.suggestions.find((s) => s.to === selected && s.from === data.currentUserId));
  let profile = $derived(data.profiles.filter((p) => p.userId === selected).sort((a, b) => b.isPrimary - a.isPrimary)[0]);
</script>
<p class="eyebrow">Settle up</p><h1>Clear the slate.</h1><p class="muted">Suggested payments are calculated from current confirmed balances. Only a payment confirmed by its recipient changes balances.</p>
{#if form?.message}<p class="error" role="alert">{form.message}</p>{/if}{#if form?.success}<p class="success" role="status">{form.success}</p>{/if}
<section class="card"><h2>Your suggested payments</h2>{#if data.suggestions.length}{#each data.suggestions as suggestion}<div class="row"><span>{names.get(suggestion.from)} pays {names.get(suggestion.to)}</span><strong>{formatPaisa(suggestion.amountPaisa)}</strong>{#if suggestion.from === data.currentUserId}<button class="small" onclick={() => selected = suggestion.to}>Pay</button>{/if}</div>{/each}{:else}<p class="muted">You're all square.</p>{/if}</section>
{#if payment}<section class="card"><div class="top"><h2>Pay {names.get(payment.to)}</h2><button class="close" onclick={() => selected = null} aria-label="Close">×</button></div><p>Suggested amount: <strong>{formatPaisa(payment.amountPaisa)}</strong></p>{#if profile}<p>{profile.method.toUpperCase()} · {profile.accountTitle}</p><p>Account: <strong>{profile.accountNumber}</strong> <button class="small" onclick={() => navigator.clipboard.writeText(profile?.accountNumber ?? '')}>Copy</button></p>{#if profile.bankName}<p>Bank: {profile.bankName}</p>{/if}{#if profile.hasQr}<img class="qr" src="/profile/qr/{profile.id}" alt="Payment QR for {names.get(payment.to)}" />{/if}{:else}<p class="muted">No payment details saved. Ask {names.get(payment.to)} for their account number.</p>{/if}<form method="POST" action="?/submit" enctype="multipart/form-data"><input type="hidden" name="payeeId" value={payment.to} /><label for="amount">Amount sent (Rs.)</label><input id="amount" name="amount" type="number" min="0.01" step="0.01" max={payment.amountPaisa / 100} required /><label for="proof">Transfer screenshot</label><input id="proof" type="file" name="proof" accept="image/png,image/jpeg,image/webp" required /><button class="button submit">Submit for confirmation</button></form></section>{/if}
{#if data.incoming.length}<section class="card"><h2>Payments to review</h2>{#each data.incoming as incoming}<div class="review"><p><strong>{names.get(incoming.payerId)}</strong> says they paid {formatPaisa(incoming.amountPaisa)}</p><a href="/settle/proof/{incoming.id}" target="_blank" rel="noopener noreferrer"><img class="proof" src="/settle/proof/{incoming.id}" alt="Transfer proof" /></a><div class="buttons"><form method="POST" action="?/confirm"><input type="hidden" name="id" value={incoming.id} /><button class="button">Confirm received</button></form><form method="POST" action="?/reject"><input type="hidden" name="id" value={incoming.id} /><button class="small">Reject</button></form></div></div>{/each}</section>{/if}
{#if data.outgoing.length}<section class="card"><h2>Your payment history</h2>{#each data.outgoing as outgoing}<div class="row"><span>To {names.get(outgoing.payeeId)} <small>{outgoing.status.replaceAll('_', ' ')}</small></span><strong>{formatPaisa(outgoing.amountPaisa)}</strong></div>{/each}</section>{/if}
<style>.eyebrow{text-transform:uppercase;letter-spacing:.13em;color:#0b806b;font-weight:800;font-size:12px}.card{max-width:650px;margin-top:22px}.row{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:14px 0;border-top:1px solid #e7eee8}.small{background:#e5f1e9;border:0;border-radius:8px;padding:7px 12px;color:#165847;font-weight:700}.top{display:flex;justify-content:space-between}.close{border:0;background:none;font-size:26px}.qr{max-width:200px;max-height:200px}.proof{max-width:100%;max-height:280px;border-radius:8px}.submit{margin-top:20px}.review{border-top:1px solid #e7eee8;padding:15px 0}.buttons{display:flex;gap:8px}.buttons form{margin:0}.success{color:#147a53}.row small{display:block;color:#647b75}</style>
