<script lang="ts">
  import { enhance } from '$app/forms';
  import { invalidateAll } from '$app/navigation';
  import { onMount } from 'svelte';
  let { data, form } = $props();
  let tab = $state('pending');
  let names = $derived(new Map(data.people.map(p => [p.id, `${p.name} (@${p.username})`])));
  let cases = $derived(data.cases.filter(c => tab === 'pending' ? c.status === 'pending' : c.status !== 'pending'));
  onMount(() => { const t = setInterval(() => { if (document.visibilityState === 'visible') void invalidateAll(); }, 15000); return () => clearInterval(t); });
</script>
<p class="eyebrow">Room decisions</p><h1>Everyone gets a fair hearing.</h1><p class="muted">Four distinct roommates must agree on a verdict. The person being reviewed cannot vote. Reports alone never apply a penalty.</p>
{#if data.people.length < 5}<p class="notice">At least five approved members are needed for a verdict: the person being reviewed plus four reviewers. Reviews stay pending until enough people can vote.</p>{/if}
{#if form?.message}<p class="error" role="alert">{form.message}</p>{/if}{#if form?.success}<p class="success" role="status">{form.success}</p>{/if}
{#if data.people.some(p => p.friesOwed)}<section class="card"><h2>🍟 Fries for everyone</h2><p class="muted">Every third verified payment-avoidance incident adds one round of fries. The room creator confirms when it has been served.</p>{#each data.people.filter(p => p.friesOwed) as person}<div class="penalty"><strong>{person.name} · {person.friesOwed} round(s) owed</strong><span>{person.avoidanceStrikes} verified incidents</span>{#if data.isOwner}<form method="POST" action="?/fries" use:enhance><input type="hidden" name="id" value={person.id} /><button class="secondary">Confirm one round served</button></form>{/if}</div>{/each}</section>{/if}
<div class="tabs" aria-label="Review filter"><button class:active={tab === 'pending'} onclick={() => tab = 'pending'}>Needs a verdict</button><button class:active={tab === 'resolved'} onclick={() => tab = 'resolved'}>Resolved</button></div>
<div class="section-grid">{#each cases as review}<article class="card review"><div class="section-heading"><span class="badge">{review.kind === 'spam' ? 'Irrelevant expense' : 'Rejected share'}</span><span class="muted">{review.status}</span></div><h2>{names.get(review.accusedId)}</h2><p>{review.reason}</p><a href="/expense/{review.expenseId}">Open expense and amounts →</a><div class="vote-counts"><span><strong>{review.votes.filter(v => v.verdict === 'uphold').length}/4</strong>{review.kind === 'spam' ? ' Irrelevant' : ' Avoiding payment'}</span><span><strong>{review.votes.filter(v => v.verdict === 'dismiss').length}/4</strong>{review.kind === 'spam' ? ' Valid expense' : ' Justified rejection'}</span></div>
{#if review.status === 'pending' && review.accusedId !== data.currentUserId && !review.votes.some(v => v.userId === data.currentUserId)}<form method="POST" action="?/vote" use:enhance><input type="hidden" name="id" value={review.id} /><div class="button-row"><button class="secondary" name="verdict" value="dismiss">{review.kind === 'spam' ? 'Valid expense' : 'Rejection is justified'}</button><button class="button" name="verdict" value="uphold">{review.kind === 'spam' ? 'Irrelevant expense' : 'Avoiding payment'}</button></div></form>{:else if review.status === 'pending'}<p class="muted">{review.accusedId === data.currentUserId ? 'Other roommates will review your case.' : 'Your vote is recorded.'}</p>{/if}
<details><summary>Who voted</summary>{#each review.votes as vote}<p>{names.get(vote.userId)} · {vote.verdict === 'uphold' ? (review.kind === 'spam' ? 'Irrelevant' : 'Avoiding payment') : (review.kind === 'spam' ? 'Valid' : 'Justified')}</p>{:else}<p class="muted">No votes yet.</p>{/each}</details></article>{:else}<section class="card empty"><h2>{tab === 'pending' ? 'Nothing to review.' : 'No resolved reviews yet.'}</h2><p class="muted">Rejected shares and spam reports will appear here.</p></section>{/each}</div>
<style>.review h2{overflow-wrap:anywhere}.vote-counts{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:22px 0}.vote-counts span{background:#f1f6f2;border-radius:12px;padding:12px}.vote-counts strong{display:block;font-size:24px}.penalty{display:flex;flex-wrap:wrap;align-items:center;gap:16px;padding:14px 0}details{margin-top:18px}summary{cursor:pointer}</style>
